#! /bin/sh

rm -f TAGS

print0='-print0'
xargs='xargs -0 etags -a'
if [ "$1" = list ]; then
    print0=''
    xargs='cat'
fi
find . \( -name "*.hh" -o -name "*.h" -o -name "*.cc" -o \
       -name "*.cpp" -o -name "*.c" \) \
       -a ! -name "moc_*" -a ! -name '.#*' $print0 | $xargs
