#! /bin/sh

# Start up scons on different SConstruct files with different ways
# of bootstrapping eol_scons, and verify that they work as expected.
#
# To test with different versions of scons, try this:
#
# (alias scons=scons-3 ; . runtests)
#
# The first run with -v can be used to verify the versions of scons and the
# python interpreter that are running.

# Setup our own isolated test site_scons directory.
mkdir -p test_site_scons/site_tools
rm -f test_site_scons/eol_scons
ln -s ../.. test_site_scons/eol_scons
rm -f test_site_scons/site_tools/eol_scons_tool.py
ln -s ../../../eol_scons/tools/eol_scons_tool.py test_site_scons/site_tools

sitedir=test_site_scons

test_sconstruct() # sfile options
{
    sfile="$1"
    shift
    echo "=== Testing $sfile: scons -f $sfile $@"
    scons -v
    if scons -f $sfile "$@" ; then
        echo PASSED.
    else
        echo '*** FAILED ***'
        exit 1
    fi
}

test_sconstruct SConstruct --site-dir=test_site_scons
test_sconstruct SConsNoDefault --site-dir=test_site_scons
test_sconstruct SConsToolOnly --site-dir=test_site_scons
test_sconstruct SConsSiteTool --site-dir=test_site_scons

pytest test_*.py
