#! /bin/sh

# Start up scons on different SConstruct files with different ways
# of bootstrapping eol_scons, and verify that they work as expected.
#
# To test with different versions of scons, try this:
#
# (alias scons=scons-3 ; . runtests)
#
# The first run with -v can be used to verify the versions of scons and the
# python interpreter that are running.

# Setup our own isolated test site_scons directory.
rm -rf test_site_scons
mkdir -p test_site_scons/eol_scons
ln -sf ../../../eol_scons ../../../__init__.py test_site_scons/eol_scons
ln -sf  ../../site_tools test_site_scons

sitedir=test_site_scons

test_sconstruct() # sfile options
{
    sfile="$1"
    shift
    echo "=== Testing $sfile: scons -f $sfile $@"
    scons -v
    if scons --site-dir=$sitedir -f $sfile "$@" ; then
        echo PASSED.
    else
        echo '*** FAILED ***'
        exit 1
    fi
}

test_sconstruct SConstruct
# test_sconstruct SConstruct qt_version=6

pytest=pytest
which pytest-3 1> /dev/null 2>&1 && pytest=pytest-3
$pytest
