#! /bin/sh

# Replace all occurrences of atd_scons with eol_scons,
# convert all PKG_ defs to generate() methods, 
# make sure there's an exists() at the end if there's a generate()

for tool in $* ; do

    if grep -q '^def generate(env):' $tool ; then :
    elif grep '^def PKG_' $tool ; then
       echo $tool still has a PKG_ definition and no generate, fixing...
       sed -i -e 's/def PKG_.*(/def generate(/' \
	   -e '/^Export(.PKG_.*/d' \
	   -e '/^Return(.PKG_.*/d' $tool
    fi

    if grep -q '^def generate(env):' $tool ; then
	if grep -q '^def exists(env):' $tool ; then :
	else
	    echo $tool needs exists method, fixing...
	    cat >> $tool <<EOF

def exists(env):
    return True

EOF
	    fi
    fi

    if grep -q 'from atd_package import Package' $tool ; then
	echo fixing atd_package import...
	sed -i -e 's/from atd_package import Package/from eol_scons.package import Package/' $tool
    fi

    if grep -q atd_scons $tool ; then
	echo $tool still refers to atd_scons, fixing...
	sed -i -e 's/atd_scons/eol_scons/g' $tool
    fi

done

