#! /bin/sh

# Start up scons on different SConstruct files with different ways
# of bootstrapping eol_scons, and verify that they work as expected.
#

# Setup our own isolated test site_scons directory.
mkdir -p test_site_scons/site_tools
rm -f test_site_scons/eol_scons
ln -s ../.. test_site_scons/eol_scons
rm -f test_site_scons/site_tools/eol_scons_tool.py
ln -s ../../../tools/eol_scons_tool.py test_site_scons/site_tools

sitedir=test_site_scons

test_sconstruct() # sfile
{
    sfile="$1"
    echo "=== Testing $sfile: scons --site-dir=$sitedir -f $sfile"
    if scons --site-dir=$sitedir -f $sfile ; then
	echo PASSED.
    else
	echo '*** FAILED ***'
    fi
}

test_sconstruct SConstruct
test_sconstruct SConsNoDefault
test_sconstruct SConsToolOnly
test_sconstruct SConsSiteTool

